### PR TITLE
Update Page Layout

### PR DESCRIPTION
**Pull request by jasongao97**
This PR currently implemented the following:

- No headers/footers for non-chapter pages
- Chapter opening pages always be on the right
- Right pages show chapter title in the header (except the opening pages)
- Left pages show chapter number in the form of `Chapter 0`
- Footers include page number starting at the first page of Chapter 0

## Demo pages

image

image

Besides, I am having the following questions:

- How about headers and footers for non-chapter pages (e.g. Dedication / Appendix)
- When a blank left page appears, what should be shown in its header and footer:
	- Should it be counted in page?
	image

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @jasongao97 thank you, this is looking great! I'll ask the header question for the front matter via email.

Regarding this one:

> When a blank left page appears, what should be shown in its header and footer:
> Should it be counted in page?

I think the blank left page can have no header (as it's essentially the "first page" of a chapter, the footers can include the page numbers as normal. A blank page should definitely be counted as a "page" in the numbering!

**Comment by jasongao97** [comment]
For reference, adding the following to `page.scss` will add headers and footers for the 'Introduction chapter':

```scss
section[data-type='page']:has(#introduction) {
  page: chapter;
  counter-reset: page 1;
  prince-page-group: start;

  h1 {
    string-set: chapter-title content(), chapter-number content();
  }
}
```

**Comment by shiffman** [comment]
@jasongao97 a3bef9aa89f8293c4d4cc0fad32c5e669fe121ba is the CSS I added according to the configuration requested for the introduction right now, feel free to consolidate/improve as you see fit and eventually it will have page numbers.

**Comment by jasongao97** [comment]
2fe8147: I added Roman numeral page number to the Introduction and Acknowledgments pages.

image

Not sure if `upper-roman` is the correct type, but there are more supported styles: https://www.princexml.com/doc/gen-content/#counter-styles

**Comment by shiffman** [comment]
@jasongao97 I wonder if we should actually merge this pull request without the roman numerals so the main branch is in sync with what is currently with the publisher and then we can open a new branch for the front matter page numbers? Would you mind doing that?

The roman numerals should be lower case I believe, that is the standard format!

**Comment by jasongao97** [comment]
Got it! That make sense. I'll revert that.

**Pull request merged**
