### PR TITLE
Update running footers

### PR DESCRIPTION
**Pull request by jasongao97**
Update the running footer to the following: https://github.com/nature-of-code/noc-book-2023/issues/726#issuecomment-1933270818

> - Acknowledgments: please use the page number plus the word Acknowledgments in the footer
> - Introduction: as you have it is correct (page number + the word Introduction)
> - Chapters: as you have it is correct
> - Appendix: please use the page number plus the word Appendix in the footer
> - Blank pages: correct, nothing

### CODE REVIEW

**Comment by jasongao97** [comment]
image

image

**Comment by shiffman** [comment]
Looks great!!

**Comment by jasongao97** [comment]
@shiffman currently, there is only a 8pt margin between the title and the page number. I'm wondering if there anything to be improve in terms of design? Perhaps we can discuss during our meeting?

**Comment by shiffman** [comment]
@jasongao97 to finalize according design specified by @tuantinghuang

**Comment by jasongao97** [comment]
Updated

image

**Comment by shiffman** [comment]
Looks great! Feel free to merge when ready and I'll test!

**Pull request merged**
