### PR TITLE
Feat: Add fill-in-blank and copy feature to the codesplit block

### PR DESCRIPTION
**Pull request by jasongao97**
This PR introduces a new `Codesplit` component with the following features:

- allows for toggling visibility of answers which were defined as `<span class="blank">{{code}}</span>`
- a 'copy' button to copy the whole block in raw text to clipboard

https://github.com/user-attachments/assets/a207ca51-ef59-487a-9834-acf7a5656592

***Note: Code snippet without any blank will only have the 'copy' button***

image

Some other changes:

- code languages are now displayed
- the build process now handles HTML content within code blocks more accurately

### CODE REVIEW

**Comment by shiffman** [comment]
Thank you for this @jasongao97, it's really terrific! I have two small comments:

1. Since the entire book is JavaScript I don't think it's necessary to show the code language. It's visually very prominent and I think distracting. I'm open to discussing this though! If it's important to include maybe we can change the design to be more subtle. @tuantinghuang curious for your thoughts.

Screenshot 2024-09-22 at 11 04 03 AM

2. This is maybe a silly thing but would it be possible for the "copy" button to copy the source code with the blanks if "reveal answer" is not selected?

**Comment by shiffman** [comment]
Let's remove "JavaScript" tag for now and I'll merge this and then we can work on in a separate branch design ideas for including the language for when it is not JavaScript (cc @tuantinghuang)

**Comment by jasongao97** [comment]
Implementing the copy-with-blanks properly might take a bit more time. So, I went for a simple solution for now by disabling the feature when the answer is hidden. Let's continue the discussion in #1016 to find a better approach, and I'll be happy to add the feature!

Demo link: https://deploy-preview-1014--nature-of-code-2nd-edition.netlify.app/vectors/#exercise-14

**Comment by shiffman** [comment]
Sounds good, this actually works quite well!

**Pull request merged**
