### PR TITLE
Misc website updates

### LINKED ISSUE #940: Incorporate Chapter Openings
I believe @tuantinghuang had a design that included the chapter opening images (in addition to the quotes), do we want to bring them into the site?

Screen Shot 2024-04-20 at 10 10 50 AM

### PR DESCRIPTION
**Pull request by jasongao97**
- Add chapter opening figure with quote, resolve #940
- Keep the lighter theme color for decoration purpose, e.g. border / icon
- Add anchor links for thumbnails and titles on the examples page
- Add meta description for search engine optimization, which also improves the appearance when shared on social media, #938

### CODE REVIEW

**Comment by shiffman** [comment]
This is looking great! For the chapter openings, I would suggest the following:

* smaller font for the title/caption, also tighter fit right below the image
* paragraph should also be smaller, maybe italicized? 

Overall, I would like these openings to feel like they are something different, rather than the start of the written text of the chapter. The image can be emphasized but the caption and description should be minimized.

@tuantinghuang feel free to offer any thoughts!

**Comment by jasongao97** [comment]
Chapter opening styles update!

image

**Comment by tuantinghuang** [comment]
This looks good! I was just comparing this to our Figma file, and some things that I notice - 

* chapter title:  is it currently heavy or black? Maybe we can make it one font weight lighter? are we also using period instead of colon? eg. "Chapter 6: Physics Libraries" or "Chapter 6. Physics Libraries"
* quote: font size can be as small as the image caption title, and smaller line spacing
* image caption title: maybe also one font weight lighter?
* image caption: I might also want to make the line spacing of the caption tiny bit smaller, but looks great as is right now too!

Attaching images to compare 

Figma
Screenshot 2024-04-23 at 08 05 01

Website
Screenshot 2024-04-23 at 08 04 25


@jasongao97 I can also help editing the css code, let me know if you would prefer that! Thank you!

**Comment by jasongao97** [comment]
> chapter title: is it currently heavy or black? Maybe we can make it one font weight lighter? are we also using period instead of colon? eg. "Chapter 6: Physics Libraries" or "Chapter 6. Physics Libraries"

The font weight was 800, and I've adjusted it to 700. I also replaced the period with a colon.

> quote: font size can be as small as the image caption title, and smaller line spacing

I've reduced the font size and adjusted the line spacing. Could you assist on the CSS part? I'm unsure if the current number is appropriate, and also the spacing between the quote and the author's name?

> image caption title: maybe also one font weight lighter?

Done!

> image caption: I might also want to make the line spacing of the caption tiny bit smaller, but looks great as is right now too!

I've slightly reduced the line spacing.

**Comment by shiffman** [comment]
There are some small open items in the discussion above (for example, font size / spacing for quotes), but I think it makes sense to merge this so we can review the production site during our meeting and file new issues for additional work.

**Pull request merged**
